build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 80
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
  TooManyFunctions:
    thresholdInClasses: 20

style:
  MagicNumber:
    active: false
  ReturnCount:
    max: 3

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9_]*'  # allow Composables to start with uppercase
